language: erlang
otp_release:
  - 21.0

sudo: required

script: cargo test

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

before_script:
  - source $HOME/.cargo/env
  - kerl list installations
  - kerl list releases
